### ISSUE TITLE
OIC user not able to make API calls

### ISSUE THREAD

**Issue by Heena-tuli** [jenkinsci/oic-auth-plugin#87]
I am using Jenkins Login with Openid Connect (Amazon Cognito). I am able to use group-based authorization. I can see my groups in Granted Authorities: authenticated,<cognito group>

But when I try making API call, it gives me a "403" error saying "Missing overall read permissions". 

I am using API token created using <Jenkins url>/configure/me

It is only allowing in case I give "Read" access to the anonymous group in Jenkins, which I couldn't give in my production environment.

Issue::

Jenkins is not able to read neither SSO users authorized in groups nor in the authenticated group.
Can't we use SSO users to make API calls

**Comment by GregoireW** [comment]
I'm facing a similar issue. 

I set Overall/Read permission on Authenticated pseudo group.  User are able to use the UI, but when they call API with a token they got  "403" error saying "Missing overall read permissions".

If I add the Overall/Read permission on a specific user then this user is able to make api call.

If I call the whoAmI with the token, I got 

```
IsAuthenticated?: true
Authorities:     <<< empty >>>
```
The groups are given via the userInfo, it is expected that there is none but authenticated.

**Comment by ckolderup** [comment]
I believe this was fixed in #80, but there has not been a new release of the plugin since that code was merged almost 8 months ago.

paging @mjmbischoff and @agentgonzo who are listed as the maintainers of this plugin on https://plugins.jenkins.io/oic-auth/. Are there any plans to update the plugin at any point, or is it abandoned?

**Comment by agentgonzo** [comment]
I don't have sufficient privileges to cut a release I'm afraid.

**Comment by vanhtuan0409** [comment]
Do we have the contact of this plugin owner :D waiting for this to be released

**Comment by agentgonzo** [comment]
It looks like @LinuxSuRen has done releases before. Maybe they can help if @mjmbischoff isn't around?

**Comment by LinuxSuRen** [comment]
Sorry for the delay. I just released it.

**Comment by GregoireW** [comment]
@LinuxSuRen  Ah! I would have hoped fot the #90 in the same release as it fix an issue that is close to this one.

**Comment by vanhtuan0409** [comment]
May I know if the 1.8 release is downloadable from Jenkins Plugin Manager :D 

Check from https://plugins.jenkins.io/oic-auth/ still show 1.7 only

**Comment by LinuxSuRen** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        It will take about one or two hours to make it be available. Now 1.8 should be ok.
    
        
            
        
    
    
          
        
            
    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    
RickJenkins 中文社区（Jenkins Chinese Community）rick@jenkins-zh.cn码云       https://gitee.com/jenkins-zhGitHub   https://github.com/jenkins-zh



        
    
     
    

    On 07/1/2020 00:07，Tuấn Vương<notifications@github.com> wrote： 



May I know if the 1.8 release is downloadable from Jenkins Plugin Manager :D
Check from https://plugins.jenkins.io/oic-auth/ still show 1.7 only

**Comment by vanhtuan0409** [comment]
Hmmm, the original issue seems to persist. My OIDC provider is keycloak and api token dont have any information about keycloak groups. Checked with version 1.8
@ckolderup Do you have any further suggestion :D

**Comment by ckolderup** [comment]
@vanhtuan0409 I don't! I'm disappointed to hear it might not work. My team has not had time to upgrade yet... we have other things happening this week.

If the release doesn't fix the API permissions issue, we will probably return to our previous workaround, which was to maintain a list of individual users and give them all permissions individually instead of relying on the "authenticated" role.

**Comment by twz123** [comment]
I think this is the same as #41 ...

**Comment by abdennour** [comment]
i am facing same issue.

I have two instances of jenkins configured with the same configuration-as-code except the securityRealm: 
- first instance using crowd +  jenkins 2.253
- second instance using this plugin oci-auth + jenkins 2.278

I login to both instances, i generated API token from both.
I used Postman to make API call : 
- First instance : API calls goes successfully
- Second instance: API call responds with 403 & long HTML response : 
```html
  <!DOCTYPE html><html class=""><head resURL="/static/0d9f8e08" data-rooturl="" data-resurl="/static/0d9f8e08" data-extensions-available="true" data-unit-test="false" data-imagesurl="/static/0d9f8e08/images" data-crumb-header="Jenkins-Crumb" data-crumb-value="41b2291e18f4da9a73030bfcfee77cf724220e3a42d749c8992a5962cb5ef338">
    
    

    <title>Jenkins</title><link rel="stylesheet" href="/static/0d9f8e08/jsbundles/base-styles-v2.css" type="text/css"><link rel="stylesheet" href="/static/0d9f8e08/css/color.css" type="text/css"><link rel="stylesheet" href="/static/0d9f8e08/css/responsive-grid.css" type="text/css"><link rel="shortcut icon" href="/static/0d9f8e08/favicon.ico" type="image/vnd.microsoft.icon"><link color="black" rel="mask-icon" href="/images/mask-icon.svg"><script src="/static/0d9f8e08/scripts/prototype.js" type="text/javascript"></script><script src="/static/0d9f8e08/scripts/behavior.js" type="text/javascript"></script><script src='/adjuncts/0d9f8e08/org/kohsuke/stapler/bind.js' type='text/javascript'></script><script src="/static/0d9f8e08/scripts/yui/yahoo/yahoo-min.js"></script><script src="/static/0d9f8e08/scripts/yui/dom/dom-min.js"></script><script src="/static/0d9f8e08/scripts/yui/event/event-min.js"></script><script src="/static/0d9f8e08/scripts/yui/animation/animation-min.js"></script><script src="/static/0d9f8e08/scripts/yui/dragdrop/dragdrop-min.js"></script><script src="/static/0d9f8e08/scripts/yui/container/container-min.js"></script><script src="/static/0d9f8e08/scripts/yui/connection/connection-min.js"></script><script src="/static/0d9f8e08/scripts/yui/datasource/datasource-min.js"></script><script src="/static/0d9f8e08/scripts/yui/autocomplete/autocomplete-min.js"></script><script src="/static/0d9f8e08/scripts/yui/menu/menu-min.js"></script><script src="/static/0d9f8e08/scripts/yui/element/element-min.js"></script><script src="/static/0d9f8e08/scripts/yui/button/button-min.js"></script><script src="/static/0d9f8e08/scripts/yui/storage/storage-min.js"></script><script src="/static/0d9f8e08/scripts/polyfills.js" type="text/javascript"></script><script src="/static/0d9f8e08/scripts/hudson-behavior.js" type="text/javascript"></script><script src="/static/0d9f8e08/scripts/sortable.js" type="text/javascript"></script><link rel="stylesheet" href="/static/0d9f8e08/scripts/yui/container/assets/container.css" type="text/css"><link rel="stylesheet" href="/static/0d9f8e08/scripts/yui/container/assets/skins/sam/container.css" type="text/css"><link rel="stylesheet" href="/static/0d9f8e08/scripts/yui/menu/assets/skins/sam/menu.css" type="text/css"><link rel="stylesheet" href="/static/0d9f8e08/jsbundles/ui-refresh-overrides.css" type="text/css"><meta name="ROBOTS" content="INDEX,NOFOLLOW"><meta name="viewport" content="width=device-width, initial-scale=1"><link type="text/css" rel="stylesheet" href="https://jx-themes.devops.example.com/css/theme.indigo.css"/>
<style type="text/css">
.testcss { color: red }
</style>
<script type="text/javascript" src="https://jx-themes.devops.example.com/js/pipeline.js"></script><script src="/static/0d9f8e08/jsbundles/vendors.js" type="text/javascript"></script><script src="/static/0d9f8e08/jsbundles/page-init.js" type="text/javascript"></script><script src="/static/0d9f8e08/jsbundles/sortable-drag-drop.js" type="text/javascript"></script></head><body data-model-type="hudson.model.Hudson" id="jenkins" class="yui-skin-sam two-column jenkins-2.278" data-version="2.278"><a href="#skip2content" class="skiplink">Skip to content</a><div id="page-head"><header id="header" class="page-header"><div class="page-header__brand"><div class="logo"><a id="jenkins-home-link" href="/"><img src="/static/0d9f8e08/images/jenkins-header-logo-v2.svg" alt="[Jenkins]" id="jenkins-head-icon"><img src="/static/0d9f8e08/images/title.png" alt="Jenkins" width="139" id="jenkins-name-icon" height="34"></a></div><a href="/" class="page-header__brand-link"><img src="/static/0d9f8e08/images/jenkins-header-logo-v2.svg" alt="[Jenkins]" class="page-header__brand-image"><span class="page-header__brand-name">Jenkins</span></a></div><div class="searchbox hidden-xs"><form role="search" method="get" name="search" action="/search/" style="position:relative;" class="no-json"><div id="search-box-sizer"></div><div id="searchform"><input role="searchbox" name="q" placeholder="search" id="search-box" class="main-search__input"><span class="main-search__icon-leading"><svg viewBox="0 0 24 24" focusable="false" class="svg-icon "><use href="/static/0d9f8e08/images/material-icons/svg-sprite-action-symbol.svg#ic_search_24px"></use></svg></span><a href="https://jenkins.io/redirect/search-box" class="main-search__icon-trailing"><svg viewBox="0 0 24 24" focusable="false" class="svg-icon "><use href="/static/0d9f8e08/images/material-icons/svg-sprite-action-symbol.svg#ic_help_outline_24px"></use></svg></a><div id="search-box-completion"></div><script>createSearchBox("/search/");</script></div></form></div><div class="login page-header__hyperlinks"><div id="visible-am-insertion" class="page-header__am-wrapper"></div><div id="visible-sec-am-insertion" class="page-header__am-wrapper"></div><a href="/user/bot" class="model-link inside inverse"><svg viewBox="0 0 24 24" focusable="false" class="svg-icon am-monitor-icon"><use href="/static/0d9f8e08/images/material-icons/svg-sprite-social-symbol.svg#ic_person_24px"></use></svg><span class="hidden-xs hidden-sm">bot</span></a><a href="/logout"><svg viewBox="0 0 24 24" focusable="false" class="svg-icon "><use href="/static/0d9f8e08/images/material-icons/svg-sprite-action-symbol.svg#ic_input_24px"></use></svg><span class="hidden-xs hidden-sm">log out</span></a></div></header><div id="breadcrumbBar"><tr id="top-nav"><td id="left-top-nav" colspan="2"><link rel='stylesheet' href='/adjuncts/0d9f8e08/lib/layout/breadcrumbs.css' type='text/css' /><script src='/adjuncts/0d9f8e08/lib/layout/breadcrumbs.js' type='text/javascript'></script><div class="top-sticker noedge"><div class="top-sticker-inner"><div class="breadcrumbs__wrapper"><ul id="breadcrumbs"><li class="item"><a href="/" class="model-link inside">Dashboard</a></li><li href="/" class="children"></li></ul><div id="breadcrumb-menu-target"></div></div></div></div></td></tr></div></div><div id="page-body" class="clear"><div id="side-panel"></div><div id="main-panel"><a name="skip2content"></a><h1>Access Denied</h1><p class="error">bot is missing the Overall/Read permission</div></div><footer class="page-footer"><div class="container-fluid"><div class="page-footer__flex-row"><div class="page-footer__footer-id-placeholder" id="footer"></div><div class="page-footer__links rest_api hidden-xs"><a href="api/">REST API</a></div><div class="page-footer__links page-footer__links--white jenkins_ver"><a rel="noopener noreferrer" href="https://devops.example.com" target="_blank">Jenkins 2.278</a></div></div></div></footer><script async="true" src="/static/0d9f8e08/scripts/svgxuse.min.js" type="text/javascript"></script></body></html>
```

**Comment by fostermi** [comment]
Is this ever going to get fixed/merged or is this plugin **_abandonware_** at this point?

**Comment by abdennour** [comment]
This is an update. The admin user ( first user ) will be able to make API calls using its username/password without passing thru OIDC verficiation.

I am using the plugin: `oic-auth:1.8`
And the following configuration-as-code: 

        jenkins:
          securityRealm:
            oic:
              authorizationServerUrl: https://keycloak.company.lan/auth/realms/devops-realm/protocol/openid-connect/auth
              userInfoServerUrl: https://keycloak.company.lan/auth/realms/devops-realm/protocol/openid-connect/userinfo
              clientId: pipeline-devops-client
              clientSecret: YOURSECRETINKEYCLOAKFORTHATCLIENT
              disableSslVerification: true
              escapeHatchEnabled: true
              escapeHatchGroup: admin
              escapeHatchSecret: adminadmin
              escapeHatchUsername: admin
              fullNameFieldName: fullName
              userNameField: preferred_username
              emailFieldName: email
              groupsFieldName: groups
              logoutFromOpenidProvider: true
              scopes: "openid email profile groups"
              tokenServerUrl: https://keycloak.company.lan/auth/realms/devops-realm/protocol/openid-connect/token

**Comment by fostermi** [comment]
Configuring the escape hatch doesn't work for me at all. Trying to login to the UI, I get redirected to the `/loginError` page. Trying to use the API just gives an "Unauthorized" response. This is with Jenkins version `2.319.2-lts`. This [1] seems to imply that the escape hatch has been broken for some time. 

[1] https://github.com/jenkinsci/oic-auth-plugin/issues/105

**Comment by michael-doubez** [comment]
Escape hatch should be fixed in version 2.0.
